[package]
name = "narvie"
version = "0.1.0"
authors = ["Harry Sarson <harry.sarson@hotmail.co.uk>"]

[dependencies]
clap = "2.32.0"
rustyline = "3.0.0"
directories = "1.0.2"
log = "0.4.6"
stderrlog = "0.4.1"
prettytable-rs = "0.8.0"
byteorder = "1.3.1"
serialport = "3.2.0"
time = "0.1"
